# Directory in which to find boxes
boxdir: ~/.py21cmmc/Boxes

# Choose appropriate redshifts to calculate.
# If a list, get co-eval boxes at these redshifts.
# If a scalar, get a lightcone *starting* at this redshift.
redshifts: [9.]

# Specify Random IDS for a particular run.
# Note: this will probably change in a future release.
random_ids: (3.000000, 3.000000)

# Specify parameters that 21cmFAST uses. These are broken into flags, astro and cosmo parameters.
# Not all options are specified here, and all available parameters, along with their defaults,
# can be found using "py21cmmc defaults".
flag_options: {
    use_fcoll_table: False,
    print_lightcone_cubes: True
}

astro_parameters: {
    HII_EFF_FACTOR: 30.0,
    ION_Tvir_MIN: 4.69897
}

cosmo_parameters: {
    OMEGA_M: 0.31
}
