# Directory in which to find boxes
boxdir: ~/Documents/Projects/Foregrounds/21CMMC_NoFileIO/21CMMC_NoFileIO_Source/Boxes

# Choose appropriate redshifts to calculate (a list)
redshifts: [9.]

# Specify parameters that 21cmFAST uses. These are broken up into those found in INIT, ANAL, COSMOLOGY
# and HEAT respectively. This needs to be expanded sufficiently, but at this point is proof-of-principle.
21cmfast_init: {
    HII_DIM: 128
}

21cmfast_anal: {
}

21cmfast_cosmo: {
}

21cmfast_heat: {
}


# Fiducial model parameters.
zeta_val: 30.0
MFP_val: 15.0
TVir_val: 30000.0


# The likelihood kwargs are specific to a certain kind of likelihood, which can be pluggable.
# The following defaults correspond to the `traditional_c_based' likelihood.
# Only required/used if generating a likelihood or doing MCMC.
likelihood_kwargs: {
    telescope_name: HERA331,
    foreground_cut: 0.15,
    shot_noise_cut: 1.0,
    ModUncert: 0.10,
    zeta: 30.0,
    mfp: 15.0,
    tvir: 30000.0,
    noisedir: ~/Documents/Projects/Foregrounds/21CMMC_NoFileIO/21CMMC_NoFileIO_Source/Programs/NoiseData
}


# Set ranges for the parameters (only apply to MCMC).
# zeta_range: [5., 100.]
# mfp_range: [2., 20.]
# log10tvir_range: [4, 5.5]
